### PR TITLE
fix(button-group): add button overrides fix for button group style

### PR DESCRIPTION
**Pull request by illogikal**
#### Description

Fixes issue with button-group button overrides where the border radius styles wouldn't get passed in if you set the style of the BaseButton. Code below to reproduce.

```javascript
import React from 'react';
import {ButtonGroup} from 'baseui/button-group';
import Upload from 'baseui/icon/upload.js';
import {Button} from 'baseui/button';

export default () => (
  <React.Fragment>
    <ButtonGroup>
      <Button
        overrides={{
          BaseButton: {
            style: props => ({color: '#000'}),
          },
        }}
      >
        Label
      </Button>
      <Button
        overrides={{
          BaseButton: {
            style: props => ({color: '#000'}),
          },
        }}
      >
        Label
      </Button>
      <Button
        overrides={{
          BaseButton: {
            style: props => ({color: '#000'}),
          },
        }}
      >
        Label
      </Button>
    </ButtonGroup>
  </React.Fragment>
);
```

#### Scope

- [x] Patch: Bug Fix

### CODE REVIEW

**Comment by gergelyke** [comment]
Thanks for the contribution @illogikal ! One small comment - can we drop the new dependency? We are trying to keep the size as small as possible

**Comment by illogikal** [comment]
We could but object-path is by far the best object deep key accessor in my opinion and it could probably be sprinkled around the codebase to reduce some LOC, but I haven't looked at everything. If you insist am happy to comply, but for use cases like where I used it, it's really convenient :)

**Comment by gergelyke** [comment]
how about the following - let's merge this PR without the extra dependency, and after that we can take a look at the codebase if we should pull it in ?

**Comment by illogikal** [comment]
Fixed

**Comment by gergelyke** [comment]
it seems like there is an issue with type checking - can you run `npm test` locally and fix the issue?

**Comment by chasestarr** [comment]
we may want to wait for @sandgraham's changes to the button styles. It should remove the extra override logic when mapping over `ButtonGroup` children

**Comment by chasestarr** [comment]
thank you for the contribution @illogikal. I'm going to close this pr since the button redesign has been merged. we plan to make a release in the next couple days. Feel free to re-open if you are experiencing this problem once v7 is released

**Pull request closed without merging**
