### PR TITLE
fix(theme): use primary and mono appropriately

### PR DESCRIPTION
**Pull request by leyanlo**
#### Description

Use primary and mono appropriately. A few colors in Calendar, Toggle, and Modal are set to black, white, or primary when they should have been primary or mono.

#### Test Plan
Set primary colors to blue in light-theme/color-tokens.js or dark-theme/color-tokens.js to test:
```js
{
  primary: colors.blue400,
  primary50: colors.blue50,
  primary100: colors.blue100,
  primary200: colors.blue200,
  primary300: colors.blue300,
  primary400: colors.blue400,
  primary500: colors.blue500,
  primary600: colors.blue600,
  primary700: colors.blue700,
}
```

Calendar before: 
calendar-before
Calendar after: 
calendar-after

Toggle before: 
toggle-before
Toggle after: 
toggle-after
Toggle dark before: 
toggle-dark-before
Toggle dark after: 
toggle-dark-after

Modal before: 
modal-before
Modal after: 
modal-after

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
@leyanlo - are you using a custom theme? 🤔 I was a bit surprised by all the blues :)

**Comment by leyanlo** [comment]
> @leyanlo - are you using a custom theme? 🤔 I was a bit surprised by all the blues :)

We are still on blue! Have a ticket in the backlog to migrate to black. In the meantime it’s probably helpful to test with other primary colors in case other non-black companies or applications wish to use this open source project ;-)

**Comment by sandgraham** [comment]
Is this waiting on anything or can we merge in?

**Comment by leyanlo** [comment]
Would love to get this merged please!

**Comment by sandgraham** [comment]
Cool - will release a new minor in a minute.

**Comment by leyanlo** [comment]
🎉

**Pull request merged**
