### PR TITLE
fix(file-uploader): dropzone upgrade vite build fix (#5200)

### LINKED ISSUE #5084: FileUploader opens file dialog twice
This also happens on the official Base Web homepage. (https://baseweb.design/components/file-uploader/)
This did not happen on Base Web v11.x.

## Current Behavior
When I click the "Browse files" button and select a file to upload, the file dialog opens again and requires me to select the file again.

## Expected Behavior
After selecting a file, the file should be selected and the file dialog should not open.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v12.0.0  |
| React   | v17.0.2 |
| browser | Chrome 103 |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### LINKED ISSUE #5200: FileUploader doesnt work when using vite build
The file uploader does not work correctly with vite builds.
Sandbox demo of vite build:
https://codesandbox.io/s/base-web-fileuploader-vite-build-zte2jy?file=/src/App.tsx
(doesn't auto-refresh since its a build just hit refresh to see changes, and also open in a new window to see console errors)

## Current Behavior
The OnDrop callback is never called due to 
`Uncaught (in promise) TypeError: dist is not a function` 
which seems to be from react-dropzone as pointed out by @TomasMoratoPerezPorro in issue #4896
Unfortunately upgrading to later versions of react-dropzone may cause the file dialog to open twice as demonstrated in issue #5084. 
https://codesandbox.io/s/base-web-fileuploader-vite-build-upgraded-react-dropzone-n4grdx?file=/yarn.lock:60942-60947
The above sandbox shows the issue in #5084.

## Expected Behavior
The OnDrop callback is to be called successfully.

## Your Environment
(for more details refer to sandbox above)

| Tech    | Version |
| ------- | ------- |
| Base UI | 12.2.0  |
| React   |  17.0.2     |
| browser | 106.0        |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by im28**
Fixes #5200 Fixes #5084

#### Description
Updated react-dropzone to v10.2.2 to resolve issue #5200 
Added correct props to react-dropzone (noClick) to ensure that #5084 doesnt happen, and added a unit test for that.

#### Scope
Patch: Bug Fix

### CODE REVIEW

**Comment by im28** [comment]
@tajo @chasestarr @lhbrennan, I would love to hear your feedback on this PR. 
btw please refer to the codesandboxes provided in the issue referenced #5200, for some reason codesandbox-ci seems not to showcase the problem.

**Comment by martinlistiak** [comment]
I would love to see this merged.

**Comment by cchampou** [comment]
Resolving to `react-dropzone@10.2.2` seems to solve the issue on my side, although I have this "double click" issue, hence your code, which looks good to me. I'll try to confirm good correction of everything with this PR's code. Thanks @im28 for this PR!

**Comment by ecarrera** [comment]
I'm facing the same problem, changed my project bundler from Webpack to Vite and now `FileUploader` is not working. Gonna have to implement my own file picker by now.

Screenshot 2023-06-13 at 16 13 38

It could be great if the new version 13 have a patch for this.

cc: @lhbrennan @chasestarr

**Pull request closed without merging**
