### PR TITLE
Check that ref for ID exists in treeItemRefs

### PR DESCRIPTION
**Pull request by jayantbh**
#### Description

This PR will resolve this error that I keep running into:
image

#### Scope
Patch: Bug Fix

### CODE REVIEW

**Review by sandgraham — APPROVED** [review]

**Review by sandgraham — CHANGES_REQUESTED** [review]
Ah actually we don't have a loader for `?` yet. Can we do this the ol' fashioned way?

**Comment by jayantbh** [comment]
Aha. Noted. Will do.

**Comment by jayantbh** [comment]
@sandgraham, done.

**Review by chasestarr — APPROVED** [review]
Thank You

**Pull request merged**
