### PR TITLE
fix(datepicker): properly handling min and max values

### LINKED ISSUE #2418: Datepicker: years before 2000 cause several issues
https://codesandbox.io/s/datepicker-tkn6r

## Current Behavior

If I set the current value or the minDate of a Datepicker to a date before Y2K, I see the following behaviors:

(See the [linked codesandbox](https://codesandbox.io/s/datepicker-tkn6r) for an example that behaves problematically)

- I can't use the left-arrow button to select months _before_ Jan 2000 (despite my minDate being earlier than that):

disabled_left_arrow

- I _can_ use the right-arrow button to select months _after_ my maxDate:
right_arrow_should_disable

- The month dropdown doesn't contain any values:
no_results

## Expected Behavior

- Should be able to select dates prior to 2000, if they're within my date range
- Should not be able to select dates greater than my date range, even if my minDate is prior to 2000
- I should see values in the month dropdown, even if my minDate is prior to 2000

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.25.0  |
| React   |    16.8.6     |
| browser |    Chrome Version 78.0.3904.108 (Official Build) (64-bit)     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by kantuni**
Fixes #2418.

#### Description
Compare with props if they are set, otherwise compare with constants.

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
thank you @kantuni - can you also add a regression test please?

**Comment by gergelyke** [comment]
@kantuni can you help us with the regression test? if not, that's fine too, I can add it

**Comment by gergelyke** [comment]
@kantuni do you plan to work on this, or do you want us to take this on?

**Comment by kantuni** [comment]
@gergelyke, I don't think I will have time to do it these couple of weeks. You guys can take it.

**Comment by gergelyke** [comment]
okay, I'll take this over - thank you @kantuni

**Pull request closed without merging**
