### PR TITLE
docs(setup): fix styletron section

### PR DESCRIPTION
**Pull request by vfonic**
#### Description

I noticed that the text read:

> **an** example declaration**s**

So I thought I'll just fix it (can't use `an` and plural)

#### Scope

- [x] Docs: Fix typo 😇 
- [ ] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
thank you @vfonic

**Comment by gergelyke** [comment]
@vfonic would you mind signing the CLA?

**Comment by vfonic** [comment]
I just signed the CLA. I think it's useless, but please, do point me where CLA was actually useful and I'd be glad to stand corrected.

**Comment by gergelyke** [comment]
> I just signed the CLA. I think it's useless, but please, DO point me where CLA was actually useful and I'd be glad to stand corrected.

thank you! it's a legal thing, we just have to do it - sorry about the inconvenience!

**Pull request merged**
