### PR TITLE
fix(popover): avoid infinite focus loop

### PR DESCRIPTION
**Pull request by chasestarr**
Fixes: https://github.com/uber/baseweb/issues/2685

#### Description

infinite loop between focusing the content and the anchor element
on anchor hover, content focuses if it contains a tabbable element this is why the scenario includes tabIndex prop
on anchor click, the popover closes because of onClickOutside rules
anchor click focuses it, thus opening the popover and focusing popover content
content focus causes the anchor to blur, which causes the popover to close
because of how the focus lock was configured it refocused the anchor which restarts the loop

#### Scope

- [x] Patch: Bug Fix

### CODE REVIEW

**Comment by houmark** [comment]
I was about to create a test case on this one. In Chrome we see the browser scrolling to the top when clicking a button that opens a popover since a few releases ago. Seems that Safari is handling it better.

**Comment by chasestarr** [comment]
> I was about to create a test case on this one. In Chrome we see the browser scrolling to the top when clicking a button that opens a popover since a few releases ago. Seems that Safari is handling it better.

Focus was added in [this pr](https://github.com/uber/baseweb/pull/2650), which probably should have defaulted to off (going to consider making this change in a separate pr).  Scrolling to the top sounds its own issue, or are you noticing a similar loop?

**Comment by houmark** [comment]
Not exactly sure, I just received a user report on the behavior and then I went to test in Safari and didn't see an issue.

Then I tested in Chrome and it does it pretty consistently in the use case we have (flex grid table, with an expand that opens a Grid). Anyways, my plan is to see if this PR does any changes to that behavior in Chrome and if not, then I will try to make a Code Sandbox with a simplified reproducible test case.

**Comment by chasestarr** [comment]
this could be some relevant info to you if it's only reproducible in chrome https://github.com/theKashey/react-focus-lock#focusing-in-osx-safarifirefox-is-strange

**Comment by houmark** [comment]
So `focusLock={false}` seems to correct the bad behavior in our use case. Still testing, but this may be an indicator of a bug with the feature or just incorrect use which happens due to being default to `true`.

**Pull request merged**
