### PR TITLE
fix(textarea): exports ADJOINED

### LINKED ISSUE #3660: [Textarea] documentation breaks on changing adjoined knob
In the Textarea documentation page,
changing the value of adjoined prop breaks and gives the error
`TypeError: Cannot read property 'left' of undefined`
Reproduce [video](https://www.loom.com/share/81078fd4eee4433382c675d5fe5d20a9)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 9.95.2  |
| React   |    ^16.9.0     |
| browser |     Chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by stackyism**
Fixes #3660 

#### Description

Exported ADJOINED constant from textarea/index.js similar to STATE_CHANGE_TYPE & SIZE which were internally fetched from input/constants.js

Reproduced Error : [Video](https://www.loom.com/share/81078fd4eee4433382c675d5fe5d20a9)

Working Fix: [Video](https://www.loom.com/share/70dc89c5ac76466d8d22e4888f1f5662)

#### Scope
Patch: Bug Fix

### CODE REVIEW

**Comment by chasestarr** [comment]
Thank you for putting up this PR @stackyism. The `ADJOINED` enum does not really apply to the `Textarea` component and is most applicable to the `Input`. We re-use the input config for the interactive docs. Can you please omit this prop here? https://github.com/uber/baseweb/blob/master/documentation-site/components/yard/config/textarea.ts#L21

**Comment by stackyism** [comment]
@chasestarr Thank you so much for your prompt reply.
I've made the changes as asked.

Please let me know if any further action is required from my side.
Thanks!

**Comment by chasestarr** [comment]
Looks good, thanks! Please review the CLA [here](https://github.com/uber/baseweb/pull/3661#issuecomment-676108429) and then we can land

**Comment by stackyism** [comment]
@chasestarr completed CLA.
Thanks!

**Comment by chasestarr** [comment]
Can you please double check? It looks like there is an error in the comment above

**Comment by stackyism** [comment]
@chasestarr Apologies! 
Actually, these commits picked up my work global git config for its author.

I've made a new Pull Request https://github.com/uber/baseweb/pull/3669 with correct author as email address.
We can close this one.
Thanks!
Sorry for the inconvenience.

**Pull request closed without merging**
