### PR TITLE
Add ES-AR localization

### PR DESCRIPTION
**Pull request by byeze**
#### Description
Added Spanish - Argentina localization for the components.

#### Scope
**Minor:** New Feature / Localization

### CODE REVIEW

**Comment by tajo** [comment]
Oh thanks. Not sure if we want to maintain these. Wdyt @chasestarr?

**Comment by tajo** [comment]
Ok, we want to merge it. It seems the low annotation is missing ([eslint failing](https://buildkite.com/uberopensource/baseweb/builds/18045#4664d56f-103d-4594-8721-f1cf49958435/182-189)). Could you please fix that?

**Comment by byeze** [comment]
Sorry for the delay! I added the annotation in my file and corrected a typo

**Review by chasestarr — APPROVED** [review]
Thank You

**Pull request merged**
