### PR TITLE
fix(theme): export createDarkTheme and createLightTheme

### PR DESCRIPTION
**Pull request by GuilhermeGuiuler**
#### Description

Export `createDarkTheme` and `createLightTheme` from root index. Fixes #3198.

#### Scope

- [x] Patch: Bug Fix

### CODE REVIEW

**Comment by sandgraham** [comment]
@GuilhermeGuiuler could you sign the CLA? I can merge this in right away once that is taken care of.

**Comment by GuilhermeGuiuler** [comment]
> @GuilhermeGuiuler could you sign the CLA? I can merge this in right away once that is taken care .
Hello, I already signed the CLA

**Comment by GuilhermeGuiuler** [comment]
@sandgraham Hello, I already signed the CLA

**Comment by sandgraham** [comment]
@GuilhermeGuiuler Could you check one more time on the CLA? It doesn't look like it went through the first time.

**Comment by GuilhermeGuiuler** [comment]
> @GuilhermeGuiuler Could you check one more time on the CLA? It doesn't look like it went through the first time.

I go to the link to sign the CLA, and write it here under the title "You have signed the CLA for uber / baseweb"

**Comment by sandgraham** [comment]
Okay, no problem- thanks for the contribution @GuilhermeGuiuler !

**Pull request merged**
