### PR TITLE
fix(various): do not pass item as prop to styled component

### PR DESCRIPTION
**Pull request by leyanlo**
#### Description

Do not pass item as prop to styled components to avoid appearing in the DOM.

Select before: 
Screen Shot 2019-12-11 at 3 09 37 AM
Select after: 
Screen Shot 2019-12-11 at 3 17 22 AM

Phone Input before: 
phone-input-before
Phone Input after: 
phone-input-after

Side Navigation before: 
side-navigation-before
Side Navigation after: 
side-navigation-after

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by chasestarr** [comment]
thanks for improving this! can you resolve the regression shown in the vrt?

**Comment by leyanlo** [comment]
@chasestarr I added a `$` prefix to item, which should resolve the vrt regression. Not sure if this makes the most sense, since `$` prefixes are designed for sending props to styled components, but we’re using it instead to send to an override in your menu adapter example..

**Comment by chasestarr** [comment]
we'll need to hold off on merging to the next major because of the prop name change

**Comment by tajo** [comment]
> we'll need to hold off on merging to the next major because of the prop name change

Hm, about doing a bit workaround in meantime and wrapping `StyledItemList` with another React component just to filter our the `item` prop?

**Comment by chasestarr** [comment]
that sounds fine to me

**Comment by leyanlo** [comment]
Update with workaround

**Comment by leyanlo** [comment]
Is this snapshot correct? Not sure if it is supposed to look like this but updated anyway..

**Pull request merged**
