### PR TITLE
fix(layout-grid): fix ALIGNMENT enum

### PR DESCRIPTION
**Pull request by AEgan**
#### Description

Fixes the ALIGNMENT enum to work with type checking + usage with the `align` prop when using typescript

[constants.js](https://github.com/uber/baseweb/blob/45e52ab24c18a8df7f6025cdb3f716030f8e5a1a/src/layout-grid/constants.js#L14-L18)

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
@AEgan would you mind signing the CLA please?

**Comment by AEgan** [comment]
@gergelyke I signed it already, but I don't think the mergify bot has? 

https://github.com/uber/baseweb/pull/3266#issuecomment-619066557

**Comment by gergelyke** [comment]
oh sorry, you are right - legal approved that bot, so it will be added to the whitelist eventually

**Comment by AEgan** [comment]
🙌 thanks, friends

**Pull request merged**
