### PR TITLE
Shadow DOM support

### PR DESCRIPTION
**Pull request by gevgeny**
Fixes https://github.com/uber/baseweb/issues/4277

Additionally added:
- e2e tests for shadow DOM cases of the updated components
- e2e test utils for shadow DOM testing 
- Warning message when the library used inside of shadow DOM with `mode="closed"` since in this cause even `event.composedPath()` will not fetch a proper event target

#### Scope
Patch: Bug Fix

### CODE REVIEW

**Comment by gevgeny** [comment]
@chasestarr @tajo @williamernest Could you please help me to run build, so I can verify all the checks and tests?

**Comment by gevgeny** [comment]
@williamernest Could you please help me with tests? The all are passed locally, but fails on this CI 😐

**Comment by gevgeny** [comment]
@williamernest Looks like the merge didn't help, do you have any ideas why test may not pass?

**Comment by chasestarr** [comment]
Can you please try running locally again? We've made some changes recently to align the puppeteer versions between local and CI. I'm not familiar with shadow dom, so not able to help out very effectively.

**Comment by gevgeny** [comment]
@chasestarr Yes, now the tests fail locally too. I also see that now e2e tests run on react v16 while before your update they run on react v17. And looks this is the reason of the problem, react works properly with shadow DOM only starting from v17 (see https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation) and in order to baseUI's mouse events work within shadow DOM user needs to run baseui with react v17. 
Does baseUI support react 17 officially?

**Comment by gevgeny** [comment]
@chasestarr What about adding such util into `helpers/index.js`:
```js
...

const describeIfReactGreaterThan16 = React.version.startsWith('17')
  ? describe.skip
  : describe;
```

and then in `select-shadow-dom.e2e.js`:
```js
const { describeIfReactGreaterThan16 } = require('../../../e2e/helpers/index.js');

describeIfReactGreaterThan16('select in shadow DOM', () => {
  it('should pass', () => { ... }
});
```

**Comment by chasestarr** [comment]
That sounds fine to me

**Comment by gevgeny** [comment]
@chasestarr Added a condition. Let's try to build this one.

**Comment by chasestarr** [comment]
Sorry to say, but we're going to decline adding broad support for shadow-dom. We may consider landing this change once our company is updated to react v17 but for the time-being we'd like to focus on the plain dom support. Apologies again for not reaching this decision sooner before you wrote the code.

**Comment by gevgeny** [comment]
@chasestarr What If I remove all the tests and leave only `event.target` -> `event.composedPath()[0]`replacement? It is fully back compatible and all the old tests pass for both react16 and react17.

**Pull request closed without merging**
