### PR TITLE
fix(input): vertically align 'show password' icon button

### PR DESCRIPTION
**Pull request by derekmisler**
### Description

Prior to this change, the icon button for showing/hiding the text in a password-type input was vertically aligned to the top of the input. This change vertically centers the icon to match the other input icons.

Adds `alignItems: 'center'` to `StyledMaskToggleButton`.
Fixes https://github.com/uber/baseweb/issues/3121

Before:
Screen Shot 2020-03-26 at 9 10 16 AM

After:
Screen Shot 2020-03-26 at 9 08 55 AM

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by derekmisler** [comment]
I'm not able to add labels to issues or PRs yet.

**Comment by gergelyke** [comment]
@sandgraham I wonder, how come it was not caught by VRT?

**Comment by sandgraham** [comment]
@gergelyke This was on Firefox.

**Comment by gergelyke** [comment]
oooh, understood, thank you

**Pull request merged**
