### PR TITLE
feat(slider): add step to useThumbOverlap for decimals

### LINKED ISSUE #2552: Step and decimals past the tenth place
## Feature description
The ability to have the Slider value to have the same number of decimals as the step definition. 

Pending the resolution of [this bug](https://github.com/tajo/react-range/issues/53) in [react-range](https://github.com/tajo/react-range), a `decimal` or `step` parameter  to the `useThumbOverlap` function for the [slider component](https://github.com/uber/baseweb/blob/master/src/slider/slider.js) will need to be passed

### PR DESCRIPTION
**Pull request by rastalamm**
Fixes #2552 

#### Description

When using `useThumbOverlap` for the Slider, it now passes the `step` value so it can determine the number of decimal places to use.

#### Scope

- [x] Minor: New Feature

### CODE REVIEW

**Comment by gergelyke** [comment]
@rastalamm can you update your PR with merging in the VRT PR?

**Comment by rastalamm** [comment]
> @rastalamm can you update your PR with merging in the VRT PR?

All set! Lmk if there is anything else I need to do

**Comment by gergelyke** [comment]
thank you @rastalamm

**Comment by gergelyke** [comment]
for the record, I should have merged this a patch commit

**Pull request merged**
