### PR TITLE
fix(layout-grid): enable conditional rendering

### PR DESCRIPTION
**Pull request by gwuah**
Fixes https://github.com/uber/baseweb/issues/2908

#### Description

This pr contains a fix that enables users to conditionally render a grid.

#### Scope

- [ x] Patch: Bug Fix

### CODE REVIEW

**Comment by chasestarr** [comment]
Thanks @gwuah - you can run `yarn flow` locally to see how static type checking fails

**Comment by gwuah** [comment]
Hi @chasestarr,
So I ran the command locally and I saw the issue.
I tried adding null to possible child types(see image below) but that broke a lot of things.
I can confirm the fix works though. I just want to know if there is a better to test my fix? 

Screen Shot 2020-03-04 at 10 22 38 AM

**Comment by gwuah** [comment]
Okay, so turns out I placed the `null` in the wrong position. 
Sorry for the notification. I've updated the pull request.

**Comment by chasestarr** [comment]
Thank you

**Pull request merged**
