### PR TITLE
Release v9.96.0

### PR DESCRIPTION
**Pull request by sandgraham**

### CODE REVIEW

**Comment by chasestarr** [comment]
Alpha CI fails on this line https://github.com/uber/baseweb/blob/master/src/tag/styled-components.js#L54 `Cannot read property 'includes' of undefined`

**Comment by sandgraham** [comment]
@chasestarr fix in #3689.

**Comment by chasestarr** [comment]
> @chasestarr fix in #3689.

Nice, FYI you'll need to open a new release PR to start alpha CI again. This is the bug I was talking about yesterday

**Comment by sandgraham** [comment]
> > @chasestarr fix in #3689.
> 
> Nice, FYI you'll need to open a new release PR to start alpha CI again. This is the bug I was talking about yesterday

NP - will open a new one.

**Pull request closed without merging**
