### PR TITLE
fix(button-group): add example for responsive styling

### LINKED ISSUE #3448: ButtonGroup responsive styling
ButtonGroup components do not line wrap - they should line wrap responsively if the container is smaller than the group.

## Current Behavior
buttons do not wrap to next line

## Expected Behavior
buttons should be pushed onto next line

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v?.?.?  |
| React   |         |
| browser |         |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #3448

#### Description
Added an example using flex-wrap property to button-group so that the buttons can wrap on small screens

#### Scope
Minor: Docs

### CODE REVIEW

**Comment by williamernest** [comment]
This change seems more appropriate as an override and not something we want as part of our core use case.

**Comment by im-adithya** [comment]
@williamernest That's what I initially thought of, but then I proceeded to add it as the issue (#3448) wasn't closed.
Should I close this then?

**Comment by williamernest** [comment]
We've decided to add an example on the doc site of this behavior, but to leave the component alone. Since this is such a small /straightforward change, it doesn't make a lot of sense to hide it behind a prop so overrides seems like the best approach. Thanks for the contribution. We're happy to help you land a doc-site example if you're still interested in resolving the issue.

**Comment by im-adithya** [comment]
Done!

**Review by williamernest — APPROVED** [review]

**Pull request merged**
