### PR TITLE
fix(spinner): only warn on usage outside of baseui

### PR DESCRIPTION
**Pull request by chasestarr**
fixes: https://github.com/uber/baseweb/issues/2836

### CODE REVIEW

**Comment by AndrewUldin** [comment]
@chasestarr could you please also take a look at this warning? I'm getting it after updating to 9.67.2

`Warning: React does not recognize the `silenceV10DeprecationWarning` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `silencev10deprecationwarning` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by skbogner** [comment]
Me too.

**Comment by gergelyke** [comment]
@AndrewUldin would you mind creating a codesandbox for this? tried to repro it on the doc site, but couldn't (I assume, somewhere it's passed down to a Styletron component)

**Comment by AndrewUldin** [comment]
@gergelyke yes, sure: https://stackblitz.com/edit/react-crzz7k?file=Hello.js
`isLoading={true}` does that.

**Pull request merged**
