### PR TITLE
feat(components): add a mini size

### PR DESCRIPTION
**Pull request by gergelyke**
closes https://github.com/uber/baseweb/issues/2609

### CODE REVIEW

**Comment by gergelyke** [comment]
> Should we update the visual snapshots for all the affected components?

yeah, for now it's just a WIP so we can start collaborating with design (one other known issue is the multi select height, because of the added tags)

**Comment by gergelyke** [comment]
@sandgraham just updated the PR with with VRT tests

**Comment by nadiia** [comment]
The new mini size looks good! 👏

**Comment by gergelyke** [comment]
> LGTM.
> 
> The name `mini` still seems a bit funny to me, but I don't have any other ideas.
> 
> `wee`?
> `tiny`?
> `cramped`?

we could call it small? so we'd have small, compact, default and large

**Comment by houmark** [comment]
`small` or `tiny` for me :)

**Comment by gergelyke** [comment]
Just talked with design, they prefer `mini` - also, for the record, we are a bit diverged from the naming used in the design spec (small, default, large), so probably we'll have to change it in the next major

**Pull request merged**
