### PR TITLE
fix(types): refactor overrides interfaces

### LINKED ISSUE #3307: Allow to use some override types
## Current Behavior

There are some override interface from other components that i can use in typescript. I use it when I separate my styles from my components e.g

```typescript
export const AVATAR: AvatarOverrides<StyleProps> = {...}
export const BLOCK: BlockOverrides = {...}
```

But there are others that doesn't have it like the Menu Overrides, when i checked it, its not exportable. So i created one for myself

```typescript
interface MenuOverrides {
    EmptyState?: Override<any>;
    List?: Override<any>;
    Option?: Override<any>;
    ListItem?: Override<any>;
}
```

And I also noticed that the names of the other interface is not uniform, like for the Popover Overrides, its only `Overrides` and for lists its `OverridesT`.

## Expected Behavior

- All overrides interface for each component can be used (importable).
- Uniform names for overrides, like `ComponentOverrides` for easier auto-import.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | latest  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by tusharmoraye**
Fixes #3307 

#### Description

Some components didn't export the overrides interface and some exportes it as "Overrides/OverridesT". So to make it uniforms across components, I have extracted the override types in the interfaces and exported them.

#### Scope

Patch: Bug Fix

### CODE REVIEW

**Comment by RisingGeek** [comment]
Are you working in this?

**Comment by tusharmoraye** [comment]
Hi @chasestarr, Can you please let me know if any changes are required in this PR?

**Comment by chasestarr** [comment]
Sorry I assumed more changes need to be made since typescript CI is failing

**Comment by tusharmoraye** [comment]
Ok thanks, I'll check.

**Comment by tusharmoraye** [comment]
Hi @chasestarr, I have fixed the issue. Can you please review this PR?

**Review by chasestarr — APPROVED** [review]
Thank you

**Pull request merged**
