### PR TITLE
fix(tether): scheduleUpdate popper when anchor element changes (#4112)

### LINKED ISSUE #4112: Popover is not repositioning on anchor element change
## Current Behavior
Popover does not reposition when anchor element's height/width changes.  Here, dropdown does not change position as select's size increases. https://codesandbox.io/s/base-web-select-forked-yz5cc?file=/src/example.js

## Expected Behavior
It should reposition when anchor element's height/width changes. Currently, popover repositions itself when popper's height/width changes. Should do the same for anchor element as well.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.110.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by hhvys**
Fixes #4112

### CODE REVIEW

**Review by tajo — APPROVED** [review]

**Comment by tajo** [comment]
Would it be possible to write a test for this?

**Comment by hhvys** [comment]
> Would it be possible to write a test for this?

Not sure how to test this behaviour. Couldn't find any existing test for this behaviour as well.

**Comment by chasestarr** [comment]
I believe a visual regression test may be appropriate. I would create a new .scenario file reproducing the prior behavior and add a [behavior](https://github.com/uber/baseweb/blob/master/vrt/config.js) to prepare the browser page before taking the screenshot

**Comment by hhvys** [comment]
@chasestarr @tajo do you want me to add tests?

**Comment by chasestarr** [comment]
Yes, please add a test

**Comment by hhvys** [comment]
@chasestarr tests are added. Please review

**Comment by chasestarr** [comment]
Looks good. Please review and merge this PR https://github.com/hhvys/baseweb/pull/2 into your branch

**Comment by hhvys** [comment]
Thanks @chasestarr. Merged it.

**Review by chasestarr — APPROVED** [review]
Thank you

**Pull request merged**
