### PR TITLE
feat(layers): expose layers context

### LINKED ISSUE #3320: Expose LayersContext in baseweb/layer
## Current Behavior

We use BaseProvider but want to change the location of the LayersManager to somwhere higher up in our component tree because of stacking context(z-index) issues. 

We want to override the 'host' to the LayersContext. To do this, we need the LayersContext exposed in the file `baseweb/layer/index.js` so that we can inject a LayersProvider & Consumer below BaseProvider and override it.

Currently, if we import from `baseweb/layer/layers-manager`, we run into issues where multiple versions (esm, commonjs) of this module is being run creating further issues.

## Expected Behavior

Solving the path resolution issue is hard. The easy fix is to expose LayersContext in baseweb/layer/index.js

**PR** : https://github.com/uber/baseweb/pull/3321

## Your Environment - NA

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.75.1  |
| React   |  NA   |
| browser |   NA   |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by stanleyjohnson**
Fixes #3320

#### Description
We use BaseProvider but want to change the location of the LayersManager to somwhere higher up in our component tree because of stacking context(z-index) issues.

We want to override the 'host' to the LayersContext. To do this, we need the LayersContext exposed in the file `baseweb/layer/index.js` so that we can inject a LayersProvider & Consumer below BaseProvider and override it

#### Scope

Patch: Bug Fix

### CODE REVIEW

**Comment by gergelyke** [comment]
@stanleyjohnson thank you! would you mind signing the CLA please?

**Comment by nadiia** [comment]
@stanleyjohnson Feel free to ping me on the BaseWeb Slack support channel if you need any help with the z-index issue you're dealing with.

**Comment by nadiia** [comment]
@stanleyjohnson Could you sign the CLA so we can merge this change?

**Comment by stanleyjohnson** [comment]
@nadiia @gergelyke I have just signed the CLA, although it shows 'pending' on my screen

**Pull request merged**
