### PR TITLE
fix(slider): use semantic theme overrides for slider

### LINKED ISSUE #4213: Themes are not working for Slider
## Current Behavior
slider

## Expected Behavior
color of sliders expected turn red(cf0000)
it is not working on my codes and also not working on https://baseweb.design/components/slider/

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.113.0  |
| React   |         |
| browser |     chrome    |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #4213 

#### Description

- Use existing slider specific theme overrides for styling Slider related styled-components
- Remove unused slider specific theme overrides from documentation
- Remove dependency of conflicting slider theme overrides from toggle type checkbox

#### Scope
Patch: Bug Fix

### CODE REVIEW

**Comment by chasestarr** [comment]
Can you please review the VRT snapshot changes and confirm they are correct?

**Comment by akshatnitd** [comment]
@chasestarr Yes, the snapshots are correct.

**Comment by akshatnitd** [comment]
@chasestarr @tajo If this looks good, can we merge it?

**Comment by chasestarr** [comment]
> @chasestarr @tajo If this looks good, can we merge it?

Sorry for the delay. I just fixed some scripts in our internal JS code so that this change can be tested in visual regression tests before merging

**Review by chasestarr — APPROVED** [review]
Thank you

**Pull request merged**
