### PR TITLE
fix(input): add missing clearOnEscape prop to TypeScript types

### PR DESCRIPTION
**Pull request by airhorns**
closes: https://github.com/uber/baseweb/issues/3740

#### Description

Adds a new prop that's present in the flow types but not in the TypeScript types for `<Input/>`: `clearOnEscape`. Prop was added in #3497. 

#### Scope

Patch: Bug Fix

### CODE REVIEW

**Review by chasestarr — APPROVED** [review]
Thank you @airhorns

**Comment by chasestarr** [comment]
@airhorns do you mind checking the allow contributors to edit PR checkbox? I'd like to rebase before landing

**Comment by airhorns** [comment]
I couldn't find that button, is it in the repo settings for my fork? I hit the rebase button here as well.

**Comment by chasestarr** [comment]
> I couldn't find that button, is it in the repo settings for my fork? I hit the rebase button here as well.

Usually in the right-hand column, but no worries. I'll merge this in as soon as CI passes. Thank you

**Comment by airhorns** [comment]
#3760 is a duplicate of this

**Pull request merged**
