### PR TITLE
fix(typescript): add createThemedStyled & type argument to withStyle

### PR DESCRIPTION
**Pull request by amarinov**
#### Description

TS definitions lack `createThemedStyled`. PR adds that and extends the `WithStyleFn` interface with a type argument that allows for custom theme in `withStyle` HOC.

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
@amarinov the TS check is failing with the following erros:

```

$ tsc --skipLibCheck
--
  | documentation-site/examples/table/cells.tsx:31:3 - error TS2558: Expected 2 type arguments, but got 3.
  |  
  | 31   typeof StyledCell,
  | ~~~~~~~~~~~~~~~~~~
  | 32   {$isNegative: boolean},
  | ~~~~~~~~~~~~~~~~~~~~~~~~~
  | 33   Theme & {customThemeProp: string}
  | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  |  
  | documentation-site/examples/table/cells.tsx:34:17 - error TS7031: Binding element '$isNegative' implicitly has an 'any' type.
  |  
  | 34 >(StyledCell, ({$isNegative, $theme}) => ({
  | ~~~~~~~~~~~
  |  
  | documentation-site/examples/table/cells.tsx:34:30 - error TS7031: Binding element '$theme' implicitly has an 'any' type.
  |  
  | 34 >(StyledCell, ({$isNegative, $theme}) => ({
  | ~~~~~~
```

**Comment by sandgraham** [comment]
There's been a few flakey visual regression tests added in recently, so you can ignore that PR.

**Comment by amarinov** [comment]
@gergelyke fixed.

**Comment by gergelyke** [comment]
thank you

**Pull request merged**
