### PR TITLE
fix(datepicker): fix Datepicker quickSelect

### PR DESCRIPTION
**Pull request by leyanlo**
#### Description

Fix Datepicker quickSelect, which did not work on click because it would close the Calendar. The fix is to mount it to the root element in calendar.js, so click events will be accepted.

#### Test Plan

Try toggling quickSelect in Datepicker playground and see it works on click now.

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

**Comment by gergelyke** [comment]
thank you @leyanlo - would you mind adding a regression test for this?

**Comment by leyanlo** [comment]
> thank you @leyanlo - would you mind adding a regression test for this?

Done!

**Comment by gergelyke** [comment]
@leyanlo I am wondering, should we add an e2e test instead? that would codify the user story instead of the DOM structure

**Comment by leyanlo** [comment]
> @leyanlo I am wondering, should we add an e2e test instead? that would codify the user story instead of the DOM structure

Done

**Comment by gergelyke** [comment]
Thank you Leyan

**Pull request merged**
