### PR TITLE
docs(datepicker): add clearable example

### PR DESCRIPTION
**Pull request by leyanlo**
Add clearable Datepicker example.

### CODE REVIEW

**Comment by gergelyke** [comment]
I wonder, should we make this a top-level API instead?

**Comment by sandgraham** [comment]
@gergelyke that seems reasonable.

**Comment by tajo** [comment]
Nice. Yea, can we make this into the top level API?

**Comment by gergelyke** [comment]
I am closing this and opening a new one with the top-level API

**Comment by gergelyke** [comment]
followup pr https://github.com/uber/baseweb/pull/2499

**Pull request closed without merging**
